export type GatewayCapability =
  | "document.search"
  | "document.list"
  | "document.view"
  | "document.fileContent"
  | "document.create"
  | "document.update"
  | "document.comment.list"
  | "document.comment.add"
  | "user.search"
  | "user.get"
  | "slides.create"
  | "whiteboard.query"
  | "whiteboard.update"
  | "message.send"
  | "message.list"
  | "drive.root.meta"
  | "drive.folder.meta"
  | "drive.folder.list"
  | "drive.folder.create"
  | "drive.file.move"
  | "drive.file.copy"
  | "drive.file.delete"
  | "drive.task.check";

